sudo: required
services:
  - docker

before_install:
  - docker build -t prashanth/docker-app-ci-cd-test -f Dockerfile.dev .

script:
  - docker run prashanth/docker-app-ci-cd-test npm run tet -- --coverage
