sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t prashanth/docker-app-ci-cd-test -f Dockerfile.dev .

script:
  - docker run -e CI=true prashanth/docker-app-ci-cd-test npm run test
